version: '3'

services:
  book-api:
    container_name: book-api
    image: thiago1432/book-api:v1
    networks:
      - book-net
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    container_name: db-book-api
    volumes:
      - data:/var/lib/postgresql/db
    networks:
      - book-net
    environment:
      POSTGRES_DB: book
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  coupon_db:
    image: postgres
    restart: always
    container_name: db-coupon
    volumes:
      - data:/var/lib/postgresql/db
    networks:
      - book-net
    environment:
      POSTGRES_DB: coupon
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
  redis:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo
    container_name: mongodb-book
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - book-net
    ports:
      - "2181:2181"
  book-kafka:
    image: wurstmeister/kafka
    container_name: book-kafka
    networks:
      - book-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.5.15
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]

volumes:
  data:
    external: false
  redis_data:
  mongodb_data:
networks:
  book-net:
    driver: bridge