spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: admin
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      driver-class-name: org.postgresql.Driver
      hibernate:
        ddl-auto: update
      properties:
        hibernate.default_schema: book

# Redis Configuration
redis:
  port: 6379
  host: localhost
  topic:
    customer: customer
    book: book
  pool:
    maxIdle: 8 # max idle connections in the pool
    minIdle: 0 # min idle connections in the pool
    maxActive: -1 # no limit to the number of active connections
    maxWait: 30000 # time limit to get a connection - only applies if maxActive is finite

# Flyway Configuration
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:/db/migration
    check-location: false

bootstrap:
  servers: localhost:9092

topic:
  name:
    consumer: book
    producer: book
    groupId: group_id

hash:
  key:
    book: book
    customer: customer
