name: CI-CD

on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - uses: actions/checkout@v4.1.1
      - name: Auth to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      - name: Build image
        uses: docker/build-push-action@v5.1.0
        with:
          java-version: 17
          context: ./target/kotlin-book-api-0.0.1.jar
          push: true
          tags: |
            thiago1432/kotlin-book-api:v2
            thiago1432/kotlin-book-api:latest
   
